// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        // Use direct PostgreSQL URL for migrations when using Prisma Accelerate (prisma://)
        url:
            process.env['DATABASE_URL']?.startsWith('prisma://') ?
                process.env['DIRECT_DATABASE_URL']
            :   process.env['DATABASE_URL'],
    },
});
